# Generated by Django 5.2.4 on 2026-01-14 11:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geely', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['published'], 'verbose_name': 'category', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['date'], 'verbose_name_plural': 'Расходы'},
        ),
        migrations.AddField(
            model_name='category',
            name='published',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
