# Generated by Django 5.2.4 on 2026-01-14 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geely', '0002_alter_category_options_alter_expense_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-published'], 'verbose_name': 'category', 'verbose_name_plural': 'Категории'},
        ),
    ]
