# Generated by Django 5.2.4 on 2026-01-14 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geely', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['published'], 'verbose_name': 'category', 'verbose_name_plural': 'Категории'},
        ),
    ]
