# Generated by Django 5.2.4 on 2026-01-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geely', '0004_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-published'], 'verbose_name': 'category', 'verbose_name_plural': 'Категории'},
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='geely_categ_name_083720_idx',
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['-published'], name='geely_categ_publish_08eaed_idx'),
        ),
    ]
