# Generated by Django 5.2.4 on 2026-01-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geely', '0005_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='published',
            field=models.DateField(auto_now_add=True),
        ),
    ]
