# Generated by Django 5.2.4 on 2026-01-14 11:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geely', '0006_alter_category_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='published',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
