# Generated by Django 5.2.4 on 2026-01-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geely', '0007_alter_category_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['published'], 'verbose_name': 'category', 'verbose_name_plural': 'Категории'},
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='geely_categ_publish_08eaed_idx',
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['published'], name='geely_categ_publish_0816f9_idx'),
        ),
    ]
