# Generated by Django 5.2.4 on 2026-01-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geely', '0008_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='mileage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='expense',
            name='price',
            field=models.IntegerField(),
        ),
    ]
