# Generated by Django 5.2.4 on 2026-01-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geely', '0009_alter_expense_mileage_alter_expense_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['name'], 'verbose_name_plural': 'Расходы'},
        ),
        migrations.AddField(
            model_name='expense',
            name='name',
            field=models.CharField(default=''),
        ),
    ]
