# Generated by Django 5.2.4 on 2026-01-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geely', '0010_alter_expense_options_expense_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='name',
            field=models.SlugField(max_length=100),
        ),
    ]
