# Generated by Django 5.2.4 on 2026-01-14 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geely', '0011_alter_expense_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['date'], 'verbose_name_plural': 'Расходы'},
        ),
        migrations.RemoveField(
            model_name='expense',
            name='name',
        ),
    ]
