# Generated by Django 5.2.4 on 2026-01-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geely', '0012_alter_expense_options_remove_expense_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='mileage',
            field=models.IntegerField(default='-'),
        ),
    ]
