# Generated by Django 5.2.4 on 2026-01-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geely', '0014_alter_expense_mileage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='mileage',
            field=models.CharField(default='Не указан'),
        ),
    ]
