# Generated by Django 5.2.4 on 2026-01-14 13:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geely', '0015_alter_expense_mileage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Расходы'},
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense', to='geely.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='mileage',
            field=models.CharField(default='Не указан', verbose_name='Пробег'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='price',
            field=models.IntegerField(verbose_name='Стоимость'),
        ),
    ]
