# Generated by Django 5.2.4 on 2026-01-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geely', '0016_alter_expense_options_category_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d', verbose_name='Изображение'),
        ),
    ]
