# Generated by Django 5.2.4 on 2026-01-15 12:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geely', '0018_alter_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='mileage',
            field=models.CharField(default='Не указан', null=True, verbose_name='Пробег'),
        ),
    ]
