# Generated by Django 5.2.4 on 2026-01-15 12:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geely', '0020_alter_expense_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='mileage',
            field=models.CharField(default='Не указан', verbose_name='Пробег'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Стоимость'),
        ),
    ]
