# Generated by Django 5.2.4 on 2026-01-15 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geely', '0021_alter_expense_date_alter_expense_mileage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='geely.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='price',
            field=models.IntegerField(blank=True, verbose_name='Стоимость'),
        ),
    ]
