# Generated by Django 5.2.4 on 2026-01-15 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geely', '0022_alter_expense_category_alter_expense_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='geely.category', verbose_name='Категория'),
        ),
    ]
