# Generated by Django 5.2.4 on 2026-01-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geely', '0025_alter_expense_mileage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='mileage',
            field=models.CharField(blank=True, null='Не указан', verbose_name='Пробег'),
        ),
    ]
