# Generated by Django 5.2.4 on 2026-01-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geely', '0026_alter_expense_mileage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Стоимость'),
        ),
    ]
