# Generated by Django 5.2.4 on 2026-01-15 14:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geely', '0027_alter_expense_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='geely.category', verbose_name='КАТЕГОРИЯ'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='ДАТА'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='mileage',
            field=models.CharField(blank=True, null='Не указан', verbose_name='ПРОБЕГ'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='СТОИМОСТЬ'),
        ),
    ]
