# Generated by Django 5.2.4 on 2026-01-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geely', '0028_alter_expense_category_alter_expense_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='mileage',
            field=models.CharField(blank=True, default='НЕ УКАЗАН', verbose_name='ПРОБЕГ'),
        ),
    ]
