# Generated by Django 5.2.4 on 2026-01-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geely', '0030_alter_expense_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default='СЕГОДНЯ', verbose_name='ДАТА'),
        ),
    ]
