# Generated by Django 5.2.4 on 2026-01-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geely', '0032_alter_expense_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='mileage',
            field=models.CharField(null=True, verbose_name='ПРОБЕГ'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='price',
            field=models.CharField(default=1500, null=True, verbose_name='СТОИМОСТЬ'),
        ),
    ]
