# Generated by Django 5.2.4 on 2026-01-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geely', '0033_alter_expense_mileage_alter_expense_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='mileage',
            field=models.CharField(blank=True, default='НЕ УКАЗАН', verbose_name='ПРОБЕГ'),
        ),
    ]
