# Generated by Django 5.2.4 on 2026-01-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geely', '0034_alter_expense_mileage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='mileage',
            field=models.CharField(blank=True, default='НЕ УКАЗАН', null=True, verbose_name='ПРОБЕГ'),
        ),
    ]
