# Generated by Django 5.2.4 on 2026-02-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geely', '0035_alter_expense_mileage'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='product',
            field=models.CharField(blank=True, null=True, verbose_name='ПОКУПКА'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='price',
            field=models.CharField(null=True, verbose_name='СТОИМОСТЬ'),
        ),
    ]
