# Generated by Django 5.2.4 on 2026-02-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geely', '0036_expense_product_alter_expense_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='service',
            field=models.CharField(null=True, verbose_name='РЕМОНТ / ТО'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='product',
            field=models.CharField(null=True, verbose_name='ПОКУПКА'),
        ),
    ]
