# Generated by Django 5.2.4 on 2026-02-06 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geely', '0037_expense_service_alter_expense_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
